# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true
        name: PHPSESSID
        #SESSION AVEC REDIS
        # handler_id: 'snc_redis.session.handler'
        # save_path: '%env(REDIS_URL)%/sessions'
    
    cache:
        app: 'cache.adapter.redis'
        default_redis_provider: 'redis://localhost:6379'

    #esi: true
    #fragments: true
    http_client:
        default_options:
            max_redirects: 7

    default_locale: fr

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
