services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - symfony
    container_name: database

  nginx_php:
    build:
      context: .
      dockerfile: nginx_php.dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - symfony
    container_name: nginx_php

  redis:
    image: redis
    container_name: redis
    restart: always
    expose:
      - "6379"

  node:
    container_name: node
    build: 
      context: .
      dockerfile: node.dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - NODE_ENV=development

networks:
  symfony:
    driver: bridge
volumes:
  mysql-data: